// Code generated by protoc-gen-go.
// source: core/transaction/transaction.proto
// DO NOT EDIT!

/*
Package corepb is a generated protocol buffer package.

It is generated from these files:
	core/transaction/transaction.proto

It has these top-level messages:
	Data
	Transaction
*/
package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Type    string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Transaction struct {
	Hash      []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From      []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        []byte `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value     []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Nonce     uint64 `protobuf:"varint,5,opt,name=nonce" json:"nonce,omitempty"`
	Timestamp int64  `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	Data      *Data  `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
	ChainId   uint32 `protobuf:"varint,8,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	GasPrice  []byte `protobuf:"bytes,9,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit  []byte `protobuf:"bytes,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Alg       uint32 `protobuf:"varint,11,opt,name=alg" json:"alg,omitempty"`
	Sign      []byte `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "corepb.Data")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
}

func init() { proto.RegisterFile("core/transaction/transaction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x49, 0xb7, 0xfb, 0xa7, 0xb3, 0x55, 0x24, 0x78, 0x18, 0xd1, 0x43, 0xd8, 0x53, 0x4e,
	0x2b, 0xa8, 0x8f, 0xe0, 0x45, 0xf0, 0x20, 0xc1, 0xfb, 0x32, 0xdb, 0xc6, 0x6e, 0xa0, 0x4d, 0x42,
	0x13, 0x85, 0x7d, 0x27, 0x1f, 0x52, 0x92, 0xba, 0xae, 0xb7, 0xdf, 0xef, 0x9b, 0xce, 0xd0, 0x2f,
	0xb0, 0x69, 0xdc, 0xa8, 0xef, 0xe3, 0x48, 0x36, 0x50, 0x13, 0x8d, 0xb3, 0xff, 0x79, 0xeb, 0x47,
	0x17, 0x1d, 0x5f, 0xa4, 0x6f, 0xfc, 0x7e, 0xf3, 0x04, 0xe5, 0x33, 0x45, 0xe2, 0x1c, 0xca, 0x78,
	0xf4, 0x1a, 0x99, 0x60, 0xb2, 0x52, 0x99, 0x39, 0xc2, 0xd2, 0xd3, 0xb1, 0x77, 0xd4, 0x62, 0x21,
	0x98, 0xac, 0xd5, 0x49, 0x37, 0xdf, 0x05, 0xac, 0xdf, 0xcf, 0x37, 0xd3, 0xf6, 0x81, 0xc2, 0x21,
	0x6f, 0xd7, 0x2a, 0x73, 0xca, 0x3e, 0x46, 0x37, 0xfc, 0xae, 0x66, 0xe6, 0x97, 0x50, 0x44, 0x87,
	0xb3, 0x9c, 0x14, 0xd1, 0xf1, 0x6b, 0x98, 0x7f, 0x51, 0xff, 0xa9, 0xb1, 0xcc, 0xd1, 0x24, 0x29,
	0xb5, 0xce, 0x36, 0x1a, 0xe7, 0x82, 0xc9, 0x52, 0x4d, 0xc2, 0xef, 0xa0, 0x8a, 0x66, 0xd0, 0x21,
	0xd2, 0xe0, 0x71, 0x21, 0x98, 0x9c, 0xa9, 0x73, 0xc0, 0x05, 0x94, 0x2d, 0x45, 0xc2, 0xa5, 0x60,
	0x72, 0xfd, 0x50, 0x6f, 0xa7, 0x7a, 0xdb, 0xd4, 0x4d, 0xe5, 0x09, 0xbf, 0x81, 0x55, 0x73, 0x20,
	0x63, 0x77, 0xa6, 0xc5, 0x95, 0x60, 0xf2, 0x42, 0x2d, 0xb3, 0xbf, 0xb4, 0xfc, 0x16, 0xaa, 0x8e,
	0xc2, 0xce, 0x8f, 0xa6, 0xd1, 0x58, 0xe5, 0x5f, 0x59, 0x75, 0x14, 0xde, 0x92, 0x9f, 0x86, 0xbd,
	0x19, 0x4c, 0x44, 0xf8, 0x1b, 0xbe, 0x26, 0xe7, 0x57, 0x30, 0xa3, 0xbe, 0xc3, 0x75, 0xbe, 0x97,
	0x30, 0xd5, 0x0e, 0xa6, 0xb3, 0x58, 0x4f, 0xb5, 0x13, 0xef, 0x17, 0xf9, 0xcd, 0x1f, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0xf4, 0xcc, 0x22, 0x99, 0x01, 0x00, 0x00,
}
